services:
  - type: web
    name: controle-audio-flask
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
